version: '3.4'

services:
  web:
    container_name: bond_web
    build:
      context: src
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"