# Generated by Django 4.0.3 on 2022-04-14 12:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('bond_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('number_of_bonds', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('sp_of_bonds', models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(0)])),
                ('status_of_bond', models.CharField(blank=True, choices=[('available', 'AVAILABLE'), ('purchased', 'PURCHASED')], default='Available', max_length=10)),
                ('usd_rates', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_buyer_created', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_seller_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
